# Workflow to validate Cohiradia YAML Files.

name: Metadata CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Install Cohiradia
      run: curl -o /tmp/cohiradia-cli.jar https://cohiradia.radiomuseum.org/download/software/cohiradia-cli.jar
    - name: Check Metadata
      run: java -jar /tmp/cohiradia-cli.jar yaml-validate ./yaml
    - name: Check and set Identifiers
      run: java -jar /tmp/cohiradia-cli.jar yaml-generate-id ./yaml
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Set unique identifier.
    - name: Cleanup Cohiradia
      run: rm /tmp/cohiradia-cli.jar
    - name: Pull Data
      run: |
        curl -s -XPOST https://cohiradia.radiomuseum.org/api/metadata/pull
        curl -s -XPOST https://cohiradia.radiomuseum.org/api/metadata/reload
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      
